server:
  host: "localhost"
  port: 9999
  max_clients: 100
  timeout: 30

security:
  mode: "symmetric"
  keyfile: "certificates/symmetric.key"

logging:
  level: "INFO"
  file: "logs/symmetric_chat.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

client:
  auto_reconnect: true
  reconnect_delay: 5
  message_timeout: 10
