# Configuraci贸n del servidor
server:
  host: "localhost"
  port: 9999
  max_clients: 100
  timeout: 30

# Configuraci贸n de seguridad
security:
  enabled: true
  certfile: "certificates/server.crt"
  keyfile: "certificates/server.key"
  verify_mode: "CERT_NONE"  # Para desarrollo con certs auto-firmados

# Configuraci贸n de logging
logging:
  level: "INFO"
  file: "logs/secure_chat.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Configuraci贸n del cliente
client:
  auto_reconnect: true
  reconnect_delay: 5
  message_timeout: 10